'use-strict'
var React = require('react-native');
var yellow = '#FFFC31';
var black = '#393E41';
var red = '#E94F37';
var purple = '#5C415D';
var white = '#F6F7EB';
var blue = '#3B5998';
var gold = '#FFCC1F';
var darkGold = '#DE6000'
//var yellow = '#EDF518';
//var black = '#202100';

var {
  StyleSheet,
} = React


var Styles=StyleSheet.create({
  activated: {
    flex: 1,
    borderWidth: 3,
    borderColor: black,
    backgroundColor: yellow,
  },
  answer: {
    backgroundColor: black,
    borderColor: yellow,
    borderRadius: 15,
    borderWidth: 1,
    padding: 3,
    width: 89,
    height: 98,
    justifyContent: 'center',
  },
  answerText: {
    fontFamily: 'helvetica neue',
    fontSize: 15,
    color: yellow,
    backgroundColor: black,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  back: {
    fontFamily: 'helvetica neue',
    fontWeight: 'bold',
    fontSize: 30,
    color: yellow,
    backgroundColor: black,
    alignSelf: 'center',
  },
  backButton: {
    backgroundColor: black,
    borderRadius: 10,
    borderWidth: 0,
    padding: 5,
    width: 110,
    height: 60,
  },
  backgroundContainer: {
    color: black,
    backgroundColor: black,
    //flex: 1,
    height: 800,
  },
  beesWaxHeader: {
    //alignItems: 'flex-start',
    flexDirection: 'row',
    backgroundColor: black,
    padding: 10,
    height: 20,
  },
  beesWaxHeaderVertical: {
    backgroundColor: black,
    width: 10,
  },
  blackContainer: {
    flex: 1,
    height: 800,
    backgroundColor: black,
  },
  blueButton: {
    backgroundColor: blue,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: blue,
    padding: 5,
    marginTop: 0,
    marginBottom: 10,
    alignSelf: 'center',
    width: 350,
    height: 50,
    justifyContent: 'center',
  },
  bodyView: {
    flex: 1,
    height: 490,
    backgroundColor: black,
    justifyContent: 'center',
  },
  bodyy: {
    color: 'green',
    backgroundColor: 'red',
  },
  btn: {
    backgroundColor: black,
    borderRadius: 15,
    borderWidth: 0,
    padding: 5,
    width: 150,
    height: 60,
    alignItems: 'center',
  },
  button: {
    backgroundColor: red,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: red,
    padding: 5,
    marginTop: 60,
    marginBottom: 60,
    alignSelf: 'center',
  },
  buttonText: {
    fontFamily: 'helvetica neue',
    fontWeight: 'bold',
    fontSize: 30,
    color: yellow,
    backgroundColor: black,
    height: 60
  },
  categoryButton: {
    backgroundColor: black,
    borderRadius: 15,
    borderWidth: 0,
    padding: 5,
    width: 400,
    height: 60,
  },
  categoryView: {
    flex: 1,
    height: 485,
    backgroundColor: black,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  container: {
    flex: 1,
  },
  deactivated: {
    flex: 1,
    //height: 25,
    borderWidth: 1,
    borderColor: yellow,
    backgroundColor: black,
  },
  disclosureText: {
    color: 'white',
    backgroundColor: black,
    fontFamily: 'helvetica neue',
    fontSize: 13,
    paddingHorizontal: 20,
  },
  firstDemographic: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    backgroundColor: black,
    height: 100,
  },
  headerView: {
    flexDirection: 'row',
    height: 20,
    backgroundColor: 'green',
  },
  healthHome: {
    flex: 1,
    height: 650,
    backgroundColor: black,
    marginTop: 50,
    alignItems: 'center',
  },
  healthQuestionBodyView: {
    backgroundColor: black,
    height: 350,
    justifyContent: 'flex-start',
  },
  healthQuestionAnswerView: {
    backgroundColor: black,
    height: 270,
    flex: 1,
    flexDirection: 'row',
  },
  horizontalAnswer: {
    flexDirection: 'row',
    backgroundColor: black,
    alignItems: 'flex-end',
    marginLeft: 3,
    marginRight: 6,
  },
  horizontalUserChar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 60,
    //backgroundColor: 'green',
  },
  icon: {
    height: 10,
    width: 10,
    marginLeft: 5,
  },
  iconTest: {
    height: 40,
    width: 60,
    alignSelf: 'flex-start',
    marginTop: 8,
    marginLeft: 25,
  },
  iconVertical: {
    height: 8,
    width: 8,
    marginBottom: 5,
    marginLeft: 0,
  },
  infoText: {
    fontFamily: 'helvetica neue',
    fontSize: 20,
    fontWeight: 'bold',
    color: yellow,
    backgroundColor: black,
    paddingHorizontal: 5,
    paddingVertical: 10,
    marginTop: 5,
  },
  input: {
    backgroundColor: yellow,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 15,
    marginTop: 5,
    marginBottom: 60,
    height: 50,
    fontFamily: 'helvetica neue',
    fontWeight: 'bold',
    fontSize: 26,
    flex: 1,
  },
  inputTest: {
    backgroundColor: 'white',
    borderRadius: 10,
    borderWidth: 1,
    paddingLeft: 75,
    height: 60,
    width: 275,
    fontFamily: 'helvetica neue',
    fontWeight: 'bold',
    fontSize: 16,
    position: 'absolute',
    marginLeft: 20,
  },
  leftLine: {
    height: 1,
    width: 130,
    marginLeft: 20,
  },
  loginButton: {
    borderWidth: 0,
    borderRadius: 10,
    backgroundColor: gold,
    alignSelf: 'center',
    height: 70,
    width: 350,
    justifyContent: 'center',
    marginTop: 20,
    shadowColor: darkGold,
    shadowOffset: {height: 5},
    shadowOpacity: .7,
    overflow: 'hidden',
  },
  loginInput: {
    backgroundColor: yellow,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 15,
    marginTop: 30,
    marginBottom: 60,
    height: 50,
    fontFamily: 'helvetica neue',
    fontWeight: 'bold',
    fontSize: 26,
  },
  loginText: {
    color: darkGold,
    backgroundColor: gold,
    fontFamily: 'helvetica neue',
    fontSize: 30,
    fontWeight: 'bold',
    padding: 5,
    alignSelf: 'center',
    //width: 350,
    //height: 70,
    shadowOpacity: .5,
    shadowOffset: {height: 5},
    shadowColor: darkGold,
  },
  mainPageFooter: {
    flex: 1,
    height: 100,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: black,
  },
  mainPageView: {
    flex: 1,
    justifyContent: 'space-between',
  },
  more: {
    height: 50,
    width: 50,
  },
  orText: {
    color: gold,
    backgroundColor: black,
    fontFamily: 'helvetica neue',
    fontSize: 20,
    fontWeight: 'bold',
    paddingHorizontal: 20,
    alignSelf: 'center',
    marginTop: 20,
  },
  otherDemographic: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: black,
    height: 100,
  },
  passwordInput: {
    flexDirection: 'row',
    height: 60,
    //backgroundColor: 'red',
  },
  progressNode: {
    flex: 25,
  },
  questionText: {
    fontFamily: 'helvetica neue',
    fontSize: 20,
    fontWeight: 'bold',
    color: yellow,
    backgroundColor: black,
    paddingHorizontal: 10,
    paddingVertical: 30,
    alignSelf: 'center',
  },
  rightLine: {
    height: 1,
    width: 130,
    marginRight: 20,
  },
  rowContainer: {
    flexDirection: 'row',
    height: 20,
    marginTop: 20,
    justifyContent: 'space-between',
  },
  scrollView: {
    
    height: 300,
  },
  signUpButtonText: {
    fontSize: 18,
    color: white,
    backgroundColor: red,
    fontFamily: 'helvetica neue',
    paddingHorizontal: 25,
    fontWeight: 'bold',
    paddingVertical: 3,
  },
  signUpButtonTextBlue: {
    fontSize: 20,
    color: white,
    backgroundColor: blue,
    fontFamily: 'helvetica neue',
    paddingHorizontal: 25,
    fontWeight: 'bold',
    paddingVertical: 3,
    alignSelf: 'center',
  },
  signUpText: {
    alignSelf: 'center',
    fontFamily: 'helvetica neue',
    fontSize: 18,
    color: gold,
    backgroundColor: black,
    padding: 5,
  },
  smallBlackContainer: {
    flex: 1,
    backgroundColor: black,
    height: 500,
    justifyContent: 'center',
  },
  smallYellowContainer: {
    backgroundColor: black,
    alignItems: 'center',
    height: 120,
    flex: 1,
  },
  titleText: {
    fontSize: 50,
    color: gold,
    fontWeight: 'bold',
    marginTop: 40,
    marginBottom: 40,
    fontFamily: 'helvetica neue'
  },
  unchosen: {
    fontFamily: 'helvetica neue',
    fontWeight: 'bold',
    fontSize: 30,
    color: 'gray',
    backgroundColor: black,
    alignSelf: 'center',
  },
  userCharText: {
    color: 'white',
    backgroundColor: black,
    fontSize: 20,
    marginTop: 20,
  },
  usernameInput: {
    marginTop: 20,
    flexDirection: 'row',
    height: 65,
    //backgroundColor: 'green',
  },
});

module.exports = Styles;